# 膝关节超声 YOLO-seg 数据集配置
path: C:\liangz77\python_projects\github_projects\ultrasound_recog\data\yolo_seg
train: images/train
val: images/val
test: images/test

# 类别数
nc: 84

# 类别名称
names:
  0: GA滑膜
  1: GA滑膜血流
  2: GA痛风石
  3: GA积液
  4: GA结晶
  5: GA股四头肌腱
  6: GA腘窝囊肿
  7: GA软骨
  8: GA骨侵蚀
  9: GA骨皮质
  10: GA髌韧带
  11: N内侧副韧带
  12: N内侧半月板
  13: N半膜肌腱
  14: N外侧副韧带
  15: N积液
  16: N股二头肌腱
  17: N股四头肌腱
  18: N软骨
  19: N骨皮质
  20: N髂胫束
  21: N髌前浅筋膜
  22: N髌韧带
  23: N鹅足腱
  24: OA内侧副韧带
  25: OA内侧半月板
  26: OA半膜肌腱
  27: OA囊肿
  28: OA滑膜
  29: OA积液
  30: OA股二头肌腱
  31: OA股四头肌腱
  32: OA腘窝囊肿
  33: OA软骨
  34: OA骨皮质
  35: OA骨赘
  36: OA髂胫束
  37: OA髌韧带
  38: RA内侧副韧带
  39: RA内侧半月板
  40: RA半膜肌腱
  41: RA囊肿
  42: RA外侧副韧带
  43: RA滑膜
  44: RA滑膜血流
  45: RA积液
  46: RA股二头肌腱
  47: RA股四头肌腱
  48: RA腘窝囊肿
  49: RA软骨
  50: RA骨侵蚀
  51: RA骨皮质
  52: RA骨赘
  53: RA髂胫束
  54: RA髌韧带
  55: RA鹅足腱
  56: SPA-内侧副韧带
  57: SPA-半膜肌
  58: SPA-髌下深囊炎
  59: SPA-滑膜
  60: SPA-滑膜血流
  61: SPA-积液
  62: SPA-股二头肌腱
  63: SPA-股四头肌腱
  64: SPA-腘窝囊肿
  65: SPA-软骨
  66: SPA-骨侵蚀
  67: SPA-骨皮质
  68: SPA-髂胫束
  69: SPA-髌韧带
  70: SPA-鹅足腱滑囊炎
  71: 损伤-内侧副韧带
  72: 损伤-内侧半月板
  73: 损伤-外侧副韧带
  74: 损伤-滑膜囊肿
  75: 损伤-积液
  76: 损伤-股四头肌腱
  77: 损伤-髂胫束
  78: 损伤-髌前血肿
  79: 损伤-髌韧带
  80: 损伤-髌骨前浅筋膜
  81: 损伤-鹅足腱滑囊
  82: 滑膜囊肿-滑膜囊肿
  83: 滑膜囊肿-腘窝囊肿
