from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
WORKSPACE_DIR = ROOT / "workspace"
DATA_DIR = WORKSPACE_DIR / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
SHARED_DERIVED_DIR = DATA_DIR / "shared_derived"
REGISTRY_DIR = DATA_DIR / "registry"

EXPERIMENTS_DIR = WORKSPACE_DIR / "experiments"
ACTIVE_EXPERIMENTS_DIR = EXPERIMENTS_DIR / "active"
ARCHIVE_EXPERIMENTS_DIR = EXPERIMENTS_DIR / "archive"
REPORTS_DIR = WORKSPACE_DIR / "reports"

ASSETS_DIR = ROOT / "assets"
PRETRAINED_DIR = ASSETS_DIR / "pretrained"
TOOLS_DIR = ROOT / "tools"
DOCS_DIR = ROOT / "docs"
PROJECT_DOCS_DIR = DOCS_DIR / "project"

RAW_LABEL_DIR = RAW_DATA_DIR / "膝关节已标注"

CLEANED_DIR = SHARED_DERIVED_DIR / "cleaned"
COCO_DIR = SHARED_DERIVED_DIR / "coco"
MEDSAM_DIR = SHARED_DERIVED_DIR / "medsam"
MEDSAM_EMBED_DIR = SHARED_DERIVED_DIR / "medsam_embeddings"
NNUNET_DIR = SHARED_DERIVED_DIR / "nnunet"
NNUNET_PREPROCESSED_DIR = SHARED_DERIVED_DIR / "nnunet_preprocessed"
SPLITS_DIR = SHARED_DERIVED_DIR / "splits"
YOLO_DATA_DIR = SHARED_DERIVED_DIR / "yolo_seg"
CATEGORY_MAPPING_FILE = SHARED_DERIVED_DIR / "category_mapping.json"
CLEAN_REPORT_FILE = SHARED_DERIVED_DIR / "clean_report.json"

LEGACY_EXPERIMENT_ID = "exp_2026-04_fullimage_legacy_baseline"
ROI_ONLY_EXPERIMENT_ID = "exp_2026-04_roi_only_cls"

LEGACY_EXPERIMENT_DIR = ARCHIVE_EXPERIMENTS_DIR / LEGACY_EXPERIMENT_ID
LEGACY_CONFIGS_DIR = LEGACY_EXPERIMENT_DIR / "configs"
LEGACY_ARTIFACTS_DIR = LEGACY_EXPERIMENT_DIR / "artifacts"
LEGACY_REPORTS_DIR = LEGACY_EXPERIMENT_DIR / "reports"
LEGACY_LOGS_DIR = LEGACY_EXPERIMENT_DIR / "logs"

LEGACY_CLASSIFIER_DIR = LEGACY_ARTIFACTS_DIR / "classifier"
LEGACY_EVALUATION_DIR = LEGACY_ARTIFACTS_DIR / "evaluation"
LEGACY_INFERENCE_DIR = LEGACY_ARTIFACTS_DIR / "inference"
LEGACY_MEDSAM_RUN_DIR = LEGACY_ARTIFACTS_DIR / "medsam"
LEGACY_NNUNET_RESULTS_DIR = LEGACY_ARTIFACTS_DIR / "nnunet"
LEGACY_SEGMENT_DIR = LEGACY_ARTIFACTS_DIR / "segment"
LEGACY_YOLO_RUN_DIR = LEGACY_ARTIFACTS_DIR / "yolo_seg"

ROI_ONLY_EXPERIMENT_DIR = ACTIVE_EXPERIMENTS_DIR / ROI_ONLY_EXPERIMENT_ID
ROI_ONLY_CONFIGS_DIR = ROI_ONLY_EXPERIMENT_DIR / "configs"
ROI_ONLY_ARTIFACTS_DIR = ROI_ONLY_EXPERIMENT_DIR / "artifacts"
ROI_ONLY_LOGS_DIR = ROI_ONLY_EXPERIMENT_DIR / "logs"
ROI_ONLY_REPORTS_DIR = ROI_ONLY_EXPERIMENT_DIR / "reports"

MEDSAM_VIT_B_PATH = PRETRAINED_DIR / "medsam_vit_b.pth"
YOLO11M_SEG_PATH = PRETRAINED_DIR / "yolo11m-seg.pt"
YOLO26N_PATH = PRETRAINED_DIR / "yolo26n.pt"


def experiment_dir(experiment_id: str, archived: bool = False) -> Path:
    base = ARCHIVE_EXPERIMENTS_DIR if archived else ACTIVE_EXPERIMENTS_DIR
    return base / experiment_id
